# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_author_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
