# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_book_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
